-- ============================================================
-- 24_mp_preapproval.sql
-- Mercado Pago - assinatura recorrente (preapproval).
--
-- Adiciona o vinculo entre a assinatura local e a assinatura
-- recorrente do Mercado Pago, uma tabela de eventos (idempotencia
-- do webhook) e a RPC que o webhook usa para atualizar o status.
--
-- Segredos (MP_ACCESS_TOKEN / MP_WEBHOOK_SECRET) NAO ficam aqui:
-- vivem nas variaveis de ambiente das Edge Functions.
--
-- Idempotente. Depende de 18_billing.sql.
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 1. Vinculo com o preapproval do Mercado Pago
-- ------------------------------------------------------------
alter table public.assinaturas
    add column if not exists mp_preapproval_id text,
    add column if not exists mp_status          text,
    add column if not exists mp_payer_id        text,
    add column if not exists mp_iniciada_em     timestamptz,
    add column if not exists mp_atualizado_em   timestamptz;

create unique index if not exists uq_assinaturas_mp_preapproval
    on public.assinaturas (mp_preapproval_id)
    where mp_preapproval_id is not null;

-- ------------------------------------------------------------
-- 2. Eventos recebidos do webhook (idempotencia + auditoria)
-- ------------------------------------------------------------
create table if not exists public.mp_eventos (
    id            bigint generated by default as identity primary key,
    evento_id     text,                         -- x-request-id do MP (dedup)
    tipo          text,
    acao          text,
    recurso_id    text,
    payload       jsonb not null default '{}'::jsonb,
    status        text not null default 'recebido',  -- recebido|processado|ignorado|erro
    erro          text,
    criado_em     timestamptz not null default now(),
    processado_em timestamptz
);

create unique index if not exists uq_mp_eventos_evento
    on public.mp_eventos (evento_id)
    where evento_id is not null;

alter table public.mp_eventos enable row level security;

-- Ninguem alem do service_role (que ignora RLS) acessa os eventos.
revoke all on public.mp_eventos from anon, authenticated;

-- ------------------------------------------------------------
-- 3. RPC aplicada pelo webhook (somente service_role)
-- ------------------------------------------------------------
-- Mapeia o status do preapproval para o status interno e atualiza
-- a assinatura. O vencimento vem preferencialmente do
-- next_payment_date informado pelo MP (evita somar ciclos em
-- eventos repetidos).
create or replace function public.mp_aplicar_assinatura(
    p_preapproval_id text,
    p_empresa_id     uuid default null,
    p_status_mp      text default null,
    p_payer_id       text default null,
    p_valor          numeric default null,
    p_proximo_venc   date default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_emp    uuid;
    v_ciclo  text;
    v_status text;
    v_venc   date;
begin
    select a.empresa_id, a.ciclo
      into v_emp, v_ciclo
      from public.assinaturas a
     where a.mp_preapproval_id = p_preapproval_id
     limit 1;

    -- Fallback por empresa somente quando ainda nao ha preapproval vinculado
    -- (evita que um evento antigo sobrescreva uma assinatura mais nova).
    if v_emp is null and p_empresa_id is not null then
        select a.empresa_id, a.ciclo
          into v_emp, v_ciclo
          from public.assinaturas a
         where a.empresa_id = p_empresa_id
           and a.mp_preapproval_id is null
         limit 1;
    end if;

    if v_emp is null then
        return jsonb_build_object('ok', false, 'erro', 'assinatura_nao_encontrada');
    end if;

    v_status := case lower(coalesce(p_status_mp, ''))
        when 'authorized' then 'ativa'
        when 'pending'    then 'trial'
        when 'paused'     then 'inadimplente'
        when 'cancelled'  then 'cancelada'
        else null
    end;

    -- Status desconhecido: apenas registra o vínculo, sem mexer no plano.
    if v_status is null then
        update public.assinaturas
           set mp_preapproval_id = coalesce(p_preapproval_id, mp_preapproval_id),
               mp_status         = coalesce(p_status_mp, mp_status),
               mp_payer_id       = coalesce(p_payer_id, mp_payer_id),
               mp_atualizado_em  = now()
         where empresa_id = v_emp;
        return jsonb_build_object('ok', true, 'empresa_id', v_emp, 'status', 'ignorado');
    end if;

    if v_status = 'ativa' then
        v_venc := coalesce(
            p_proximo_venc,
            (greatest(coalesce((select vencimento from public.assinaturas where empresa_id = v_emp),
                               current_date), current_date)
             + case when v_ciclo = 'anual' then interval '1 year' else interval '1 month' end)::date
        );
    else
        v_venc := (select vencimento from public.assinaturas where empresa_id = v_emp);
    end if;

    update public.assinaturas
       set status             = v_status,
           mp_preapproval_id  = coalesce(p_preapproval_id, mp_preapproval_id),
           mp_status          = coalesce(p_status_mp, mp_status),
           mp_payer_id        = coalesce(p_payer_id, mp_payer_id),
           valor              = coalesce(p_valor, valor),
           vencimento         = v_venc,
           mp_atualizado_em   = now(),
           atualizado_em      = now()
     where empresa_id = v_emp;

    return jsonb_build_object(
        'ok', true, 'empresa_id', v_emp, 'status', v_status, 'vencimento', v_venc);
end $$;

revoke all on function public.mp_aplicar_assinatura(text, uuid, text, text, numeric, date) from public;
revoke all on function public.mp_aplicar_assinatura(text, uuid, text, text, numeric, date) from anon, authenticated;
grant execute on function public.mp_aplicar_assinatura(text, uuid, text, text, numeric, date) to service_role;

-- ------------------------------------------------------------
-- 4. minha_assinatura passa a expor o status do gateway
-- ------------------------------------------------------------
create or replace function public.minha_assinatura()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
    v_emp uuid := public.empresa_do_usuario();
    v jsonb;
begin
    if v_emp is null then
        return jsonb_build_object('tem_assinatura', false);
    end if;

    select jsonb_build_object(
        'tem_assinatura', true,
        'empresa_id', a.empresa_id,
        'plano_codigo', a.plano_codigo,
        'plano_nome', p.nome,
        'status', a.status,
        'ciclo', a.ciclo,
        'valor', a.valor,
        'inicio', a.inicio,
        'vencimento', a.vencimento,
        'trial_ate', a.trial_ate,
        'addon_mdf', a.addon_mdf,
        'inclui_mdf', (p.inclui_mdf or a.addon_mdf),
        'max_usuarios', p.max_usuarios,
        'recursos', p.recursos,
        'preco_mensal', p.preco_mensal,
        'preco_anual', p.preco_anual,
        'mp_status', a.mp_status,
        'mp_vinculada', (a.mp_preapproval_id is not null),
        'uso_usuarios', (select count(*) from public.usuarios u where u.empresa_id = a.empresa_id),
        'bloqueada', public.assinatura_bloqueada()
    ) into v
    from public.assinaturas a
    join public.planos p on p.codigo = a.plano_codigo
    where a.empresa_id = v_emp;

    return coalesce(v, jsonb_build_object('tem_assinatura', false));
end $$;

revoke all on function public.minha_assinatura() from public;
grant execute on function public.minha_assinatura() to authenticated;

commit;
